from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = PROJECT_ROOT / "assets"

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FONT_PATH = ASSETS_DIR / "fonts" / "Jersey15-Regular.ttf"
PLAYER_IMAGE_PATH = ASSETS_DIR / "images" / "player.png"
SHOT_IMAGE_PATH = ASSETS_DIR / "images" / "shot.png"
ASTEROID_IMAGE_PATHS = (
    ASSETS_DIR / "images" / "asteroid1.png",
    ASSETS_DIR / "images" / "asteroid2.png",
    ASSETS_DIR / "images" / "asteroid3.png",
)
MENU_FADE_DURATION = 0.45
MENU_TITLE_FONT_SIZE = 112
MENU_BUTTON_FONT_SIZE = 42
MENU_SMALL_FONT_SIZE = 26
MENU_TITLE_POSITION = (SCREEN_WIDTH // 2, 180)
MENU_START_POSITION = (SCREEN_WIDTH // 2, 350)
MENU_EXIT_POSITION = (SCREEN_WIDTH // 2, 435)
MENU_CONTROLS_POSITION = (SCREEN_WIDTH // 2, 600)
BUTTON_SIZE = (260, 62)
BUTTON_SHADOW_OFFSET = (6, 6)

COLOR_BUTTON_SHADOW = (3, 5, 12)
COLOR_BUTTON_IDLE = (12, 22, 31)
COLOR_BUTTON_SELECTED = (32, 70, 66)
COLOR_BUTTON_BORDER_IDLE = (91, 139, 131)
COLOR_BUTTON_BORDER_SELECTED = (174, 255, 222)
COLOR_BUTTON_TEXT = (235, 255, 246)
COLOR_TITLE = (224, 255, 240)
COLOR_TITLE_SHADOW = (18, 73, 65)
COLOR_CONTROL_TEXT = (91, 127, 123)

SCORE_FONT_SIZE = 38
SCORE_POSITION = (SCREEN_WIDTH - 24, 18)
SCORE_COLOR = (224, 255, 240)
SCORE_SHADOW_COLOR = (18, 73, 65)
SCORE_SHADOW_OFFSET = (3, 3)

GAME_OVER_DURATION = 2.6
GAME_OVER_APPEAR_DURATION = 0.35
GAME_OVER_DISAPPEAR_DURATION = 0.7
GAME_OVER_FONT_SIZE = 118
GAME_OVER_BAND_HEIGHT = 180
GAME_OVER_SHADE_COLOR = (9, 0, 4)
GAME_OVER_BAND_COLOR = (105, 5, 18)
GAME_OVER_TEXT_COLOR = (255, 225, 218)

PLAYER_SCALE = 2
PLAYER_RADIUS = 30
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_ANIMATION_SPEED = 0.1
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_MAX_ENTRY_ANGLE = 30
ASTEROID_MIN_ROTATION_SPEED = 40
ASTEROID_MAX_ROTATION_SPEED = 65
ASTEROID_MIN_SPLIT_ANGLE = 20
ASTEROID_MAX_SPLIT_ANGLE = 50
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2
ASTEROID_DEBRIS_MIN_COUNT = 5
ASTEROID_DEBRIS_MAX_COUNT = 10
ASTEROID_DEBRIS_MIN_SIZE = 3
ASTEROID_DEBRIS_MAX_SIZE = 8
ASTEROID_DEBRIS_MIN_SPEED = 90
ASTEROID_DEBRIS_MAX_SPEED = 240
ASTEROID_DEBRIS_MIN_LIFETIME = 0.35
ASTEROID_DEBRIS_MAX_LIFETIME = 0.75
ASTEROID_DEBRIS_MAX_ROTATION_SPEED = 420
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
